TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = cfvdccreate
FILES = cfvdccreate

#LIB_DEFS = vdf.def

LIBRARIES = vdf common $(NETCDF_LIBS) udunits2 expat

include ${TOP}/make/config/base.mk

