TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = wrfvdfcreate
FILES = wrfvdfcreate

#LIB_DEFS = vdf.def


LIBRARIES = pthread dl util m vdf python2.6 common netcdf proj expat

include ${TOP}/make/config/base.mk

