TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = wasp2raw
FILES = wasp2raw


#LIB_DEFS = vdf.def

LIBRARIES = vdf proj common $(NETCDF_LIBS) udunits2 expat

include ${TOP}/make/config/base.mk
