TOP = ../..

include ${TOP}/make/config/arch.mk

PROGRAM = datamgr
FILES = datamgr


LDFLAGS += $(EXPATLIB)

LIBRARIES = common vdf

CXXFLAGS += -I$(EXPAT_INC_PATH)

include ${TOP}/make/config/base.mk

