TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = grib2vdf

FILES = grib2vdf
HEADERS = 2vdf

LIBRARIES = vdf proj common $(NETCDF_LIBS) udunits2 expat grib_api

include ${TOP}/make/config/base.mk
