TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = raw2vdc
FILES = raw2vdc


#LIB_DEFS = vdf.def

LIBRARIES = vdf proj common $(NETCDF_LIBS) udunits2 expat

include ${TOP}/make/config/base.mk
