TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = cam2vdf
FILES = cam2vdf
HEADERS = 2vdf


LIBRARIES = vdf proj common $(NETCDF_LIBS) udunits2 expat

include ${TOP}/make/config/base.mk
