#!/bin/csh -f
# This postflight script echoes the values of the available 
# arguments and environmental variables.
#
echo "Start postflight script"
echo ""

set InstDest = $argv[2]


#
#
#
#
echo "Linking executables..."

if (! -d /usr/local/bin) then
	mkdir -p /usr/local/bin
	if ($status != 0) exit 1
endif

foreach file (raw2vdf vapor-setup.csh vapor-setup.sh vaporgui vaporversion vdf2raw vdfcreate)

	if (-e  /usr/local/bin/$file || -l /usr/local/bin/$file) then
		/bin/rm /usr/local/bin/$file
	endif

	ln -s $InstDest/VAPOR.app/Contents/MacOS/$file /usr/local/bin/$file
	if ($status != 0) exit 1
end


#
#
#
#
echo "Linking libraries..."

if (! -d /usr/local/lib) then
	mkdir -p /usr/local/lib
	if ($status != 0) exit 1
endif

foreach fullpath ($InstDest/VAPOR.app/Contents/MacOS/*.dylib $InstDest/VAPOR.app/Contents/MacOS/*.so $InstDest/VAPOR.app/Contents/MacOS/*.dlm)

	set file = `basename $fullpath`
	if (-e  /usr/local/lib/$file || -l /usr/local/lib/$file) then
		/bin/rm /usr/local/lib/$file
	endif

	ln -s $InstDest/VAPOR.app/Contents/MacOS/$file /usr/local/lib/$file
	if ($status != 0) exit 1
end

#
#
#
#
echo "Linking examples..."

if (! -d /usr/local/share/examples) then
	mkdir -p /usr/local/share/examples
	if ($status != 0) exit 1
endif

foreach fullpath ($InstDest/VAPOR.app/Contents/SharedSupport/examples/*)

	set file = `basename $fullpath`
	if (-e  /usr/local/share/examples/$file || -l /usr/local/share/examples/$file) then
		/bin/rm /usr/local/share/examples/$file
	endif

	ln -s $InstDest/VAPOR.app/Contents/MacOS/$file /usr/local/share/examples/$file
	if ($status != 0) exit 1
end

#
#
#
#
echo "Linking doc..."

if (! -d /usr/local/share/doc) then
	mkdir -p /usr/local/share/doc
	if ($status != 0) exit 1
endif

foreach fullpath ($InstDest/VAPOR.app/Contents/SharedSupport/doc/*)

	set file = `basename $fullpath`
	if (-e  /usr/local/share/doc/$file || -l /usr/local/share/doc/$file) then
		/bin/rm /usr/local/share/doc/$file
	endif

	ln -s $InstDest/VAPOR.app/Contents/MacOS/$file /usr/local/share/doc/$file
	if ($status != 0) exit 1
end
