TOP=../..

include ${TOP}/make/config/prebase.mk

PROGRAM = test_glflow
FILES = test_glflow glflow


LIBRARIES = GL GLU glut

MAKEFILE_CXXFLAGS += -g
MAKEFILE_LDFLAGS += -g -lGL -lGLU -lglut

include ${TOP}/make/config/base.mk
