TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = ncdf2vdf
FILES = ncdf2vdf


#LIB_DEFS = vdf.def
  
LIBRARIES = pthread dl util m vdf python2.6 common netcdf expat

include ${TOP}/make/config/base.mk
