TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = mom2vdf
FILES = mom2vdf


#LIB_DEFS = vdf.def

LIBRARIES = vdf common $(NETCDF_LIBS) expat

include ${TOP}/make/config/base.mk
