TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = mom2vdf
FILES = mom2vdf \
	2vdf
HEADERS = 2vdf


#LIB_DEFS = vdf.def

LIBRARIES = vdf common proj $(NETCDF_LIBS) udunits2 expat

include ${TOP}/make/config/base.mk
