TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = cart2wrfvdf
FILES = cart2wrfvdf


#LIB_DEFS = vdf.def
  
LIBRARIES = pthread dl util m vdf python2.6 common netcdf expat

include ${TOP}/make/config/base.mk
