TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = raw2wasp
FILES = raw2wasp


#LIB_DEFS = vdf.def

LIBRARIES = vdf proj common $(NETCDF_LIBS) udunits2 expat

include ${TOP}/make/config/base.mk
