TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = flashvdfcreate
FILES = flashvdfcreate flashhdf5

MAKEFILE_CXXFLAGS += -DH5_USE_16_API

ifeq ($(BUILD_GUI),1)
LIBRARIES = pthread dl util m vdf python2.6 common hdf5 netcdf expat
else
LIBRARIES = vdf common hdf5 netcdf expat
endif


include ${TOP}/make/config/base.mk
