TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = flashamr2vdf
FILES = flashamr2vdf flashhdf5


MAKEFILE_CXXFLAGS += -DH5_USE_16_API

LIBRARIES = pthread dl util m vdf python2.6 common hdf5 netcdf expat


include ${TOP}/make/config/base.mk
