TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = flashvdfcreate
FILES = flashvdfcreate flashhdf5

MAKEFILE_CXXFLAGS += -DH5_USE_16_API

LIBRARIES = common vdf hdf5 netcdf expat

include ${TOP}/make/config/base.mk
