=begin comment

$Id$

=end comment

=head1 NAME

cam2vdf - Transform CAM netCDF data into a VDC

=head1 SYNOPSIS

B<cam2vdf> [options] I<cam_ncdf_files...> I<cam_ncdf_grid_file> I<vdffile> 

=head1 DESCRIPTION

B<cam2vdf> reads 3D and 2D variables from one or more CAM output netCDF files,
as well as grid data from one CAM NetCDF file,
wavelet transforms the data, and stores it in the VDC associated with
the .vdf file I<vdffile>.

=head1 OPTIONS

=over 4

=item -vars E<lt>varsE<gt>

Variables to convert.  A colon delimited list of the 3D and 2D variables
you wish to transform. Their names must appear in the .vdf file, I<vdffile>.
The variable B<ELEVATION> will always be created. 
The default is to convert all time-varying 3D and 2D variables defined in
both the .vdf file and the CAM netCDF files.

=item -numts E<lt>numberE<gt>

Specify the maximum number of time steps to convert. After converting
B<number> time steps, no further processing will take place.

=item -level E<lt>levelE<gt> 

See raw2vdf

=item -lod E<lt>nE<gt> 

See raw2vdf (VDC2 only). 

=item -nthreads E<lt>nE<gt> 

See raw2vdf (VDC2 only). 

=item -help 

Print a usage statement and then exit.

=item -quiet 

Operate quietly, only reporting fatal errors.

=back

=head1 EXAMPLES

The command 

    cam2vdf camout1.nc camout2.nc camout3.nc mydata.vdf 

transforms all of the variables at all of the time steps found in
the CAM netCDF files B<camout1.nc>, B<camout2.nc>, and B<camout3.nc>
that match the variable names and time stamps found in B<mydata.vdf>.

The command 

    cam2vdf -varnames u:v:w camout1.nc camout2.nc camgrid.nc mydata.vdf 

is similar to the above example except that the converted variables are limited
to the three 3D velocity components, B<u>, B<v>, and B<w>.

=head1 SEE ALSO

camvdfcreate, ncdf2vdf, raw2vdf 

I<Conversion of CAM datafiles to a VAPOR VDC>

=head1 HISTORY

Last updated on $Date$
