=begin comment

$Id$

=end comment

=head1 NAME

mom2vdf - Transform MOM or POP netCDF data into a VDC

=head1 SYNOPSIS

B<mom2vdf> [options] I<mom_ncdf_file...> I<vdffile> 

=head1 DESCRIPTION

B<mom2vdf> reads 3D and 2D (spatial) variables from one or more MOM
(or POP) netCDF files, wavelet transforms the data, and stores it in the VDC
associated with the .vdf file I<vdffile>.

=head1 OPTIONS

=over 4

=item -vars E<lt>varsE<gt>

Variables to convert.  A colon delimited list of the 3D and 2D
variables you wish to transform. Their names must appear in the
.vdf file, I<vdffile>.  The default is to convert all 3D and 2D
(spatial) variables defined in both the .vdf file and the MOM/POP
netCDF files.

=item -numts E<lt>numberE<gt>

Specify the maximum number of time steps to convert. After converting
B<number> time steps, no further processing will take place.

=item -level E<lt>levelE<gt> 

See raw2vdf

=item -lod E<lt>nE<gt> 

See raw2vdf (VDC2 only). 

=item -help 

Print a usage statement and then exit.

=item -quiet 

Operate quietly, only reporting fatal errors.

=back

=head1 EXAMPLES

The command 

    mom2vdf momout1.nc momout2.nc momout3.nc mydata.vdf 

transforms all of the variables at all of the time steps found in
the MOM(or POP) netCDF files B<momout1.nc>, B<momout2.nc>, and
B<momout3.nc> that match the variable names and time stamps found
in B<mydata.vdf>.

The command 

    mom2vdf -varnames u:v:w momout1.nc momout2.nc mydata.vdf 

is similar to the above example except that the converted variables are limited
to the three velocity components, B<u>, B<v>, and B<w>.

=head1 SEE ALSO

momvdfcreate, ncdf2vdf, raw2vdf 

I<Conversion of MOM or POP datafiles to a VAPOR VDC>

=head1 HISTORY

Last updated on $Date$
