=begin comment

$Id$

=end comment

=head1 NAME

momvdfcreate - Generate a VDF metadata file for a MOM or POP data set

=head1 SYNOPSIS

B<momvdfcreate> [options] I<mom_ncdf_files...> I<vdffile>

=head1 DESCRIPTION

B<momvdfcreate> generates a .vdf metafile that defines a VAPOR Data
Collection (VDC) suitable for containing ocean simulation output
from MOM or POP models.  All of the model output NetCDF filenames
must be provided on the command line, followed 
the desired VAPOR (.vdf) output file name.  Coordinate information for
latitude, longitude, depth, and time must be contained in at least
one of the input NetCDF files.

=head1 OPTIONS

=over 4

=item -vars E<lt>varsE<gt>

A colon-delimited list of names of 2D and 3D (spatial) data variables
to include in the .vdf file.  In general, the list of variables
should be a subset of the data variables found in the MOM/POP input
files.  If this option is not present the default behavior is to
generate the list of variables from all of the 2D and 3D (spatial)
variables found in any of the MOM/POP netCDF input files.

=item -level E<lt>levelE<gt>

See vdfcreate.

=item -comment E<lt>stringE<gt>

See vdfcreate.

=item -bs E<lt>NXxNYxNZE<gt>

See vdfcreate.

=item -wname E<lt>wave_nameE<gt>

This option is for VDC2 only, see vdfcreate.

=item -cratios E<lt>vectorE<gt>

This option is for VDC2 only, see vdfcreate.

=item -help 

Print a usage statement and then exit.

=back

=head1 EXAMPLES


The command 

    momvdfcreate -vars u:v:time -level 2 mom1.nc mom2.nc mom3.nc mydata.vdf

will construct a VDF file, B<mydata.vdf> that will contain the B<u>,
B<v>, and B<temp> variable names for all time steps found in the
MOM netCDF files B<mom1.nc>, B<mom2.nc>, and B<mom3.nc>.

=head1 SEE ALSO

vdfcreate, mom2vdf,

I<Conversion of MOM or POP datafiles to a VAPOR VDC>

=head1 HISTORY

Last updated on $Date$
