=head1 NAME

ncdf2vdf - Convert NetCDF data to VAPOR data 

=head1 SYNOPSIS

B<ncdf2vdf> [options] I<metafile> I<ncdffile>

=head1 DESCRIPTION

B<ncdf2vdf>
converts a variable in the named NetCDF data file, I<ncdffile>,
into a variable in the VAPOR Data
Collection (VDC) associated with the named .vdf file, I<metafile>.
The variable name in the VDC must already be specified as either a 2D or 3D variable 
in the associated .vdf file associated with the variable in the NetCDF file. The variable name in the VDC can be established using e.g. B<vdfedit>, B<vdfcreate>, or B<wrfvdfcreate>.  
If a NetCDF dimension is one greater than the corresponding VDC dimension, 
data is averaged to the VDC dimension, to enable conversion of variables on staggered grids.  
Variables can be staggered in any or all of the three spatial dimensions.
B<ncdf2vdf> also allows for variable data to be a subarray of a higher-dimensional array; for example the spatial data may be a 3-dimensional subarray of a 4-dimensional array where the fourth dimension is Time.
In this situation the user must specify that Time is a "constant dimension", i.e. a coordinate that does not vary over the variable data being extracted.  
For each constant dimension name, the user must specify a "constant value" that is the value of the constant dimension for the data being extracted.

=head1 OPTIONS

=over 4

=item -debug

Turn on debugging mode. 

=item -quiet

Operate quietly. 

=item -help 

Print a usage statement and then exit.

=item -ts E<lt>timestepE<gt>

Specify the timestep in the VDC that will be converted; default is 0.

=item -varname E<lt>VariableNameE<gt>

Specify the name of the variable in the VDC 

=item -ncdfvar E<lt>ncdfVariableNameE<gt>

Specify the name of the variable in the NetCDF file, if it is not the same as in the VDC.

=item -dimnames E<lt>xdim:ydim:zdimE<gt>

Specify a colon-separated list of the dimension names in the NetCDF file that will be converted to X, Y, and Z dimensions in the VDC.  If the variable is 2D, the Z dimension name is ignored.  The Y dimension
must precede the X dimension in the dimension ordering associated with the variable in the NetCDF file.

=item -cnstnames E<lt>dim1:dim2:...E<gt>

In a colon-separated list, specify one or more dimension names in the NetCDF file that are held constant for this time step of the variable.  Typically time is a constant dimension name.

=item -cnstvals E<lt>val1:val2:...E<gt>

In a colon-separated list, specify the constant values that will be associated with each associated constant dimension name.   
This list must be the same length as the list of constant dimension names.

=item -level E<lt>levE<gt>

Specify the maximum refinement level of the variable that will be written to the VDC.  
By default this is the maximum refinement level of the VDC.  

=item -swapz

If specified, the Z coordinate will be reversed (largest to smallest) 

=back


=head1 EXAMPLES

The command

    ncdf2vdf -ts 3 -varname U -dimnames west_east_stag:south_north:bottom_top -cnstnames Time -cnstvals 2 vapordata.vdf wrfout1.nc 

will extract data values of the variable U at Time=2 from the WRF NetCDF file wrfout1.nc, inserting it into timestep 3 of the VAPOR VDC associated with vapordata.vdf .  
The X-dimension of the VDC should be equal to the west_east dimension of the WRF file, i.e. one less than the west_east_stag dimension of U, so that the data will be averaged in the X dimension, eliminating the staggering of the X dimension. 
The above data conversion is the same as would be performed by B<wrf2vdf> 
(with appropriate arguments).

=head1 NOTES

The dimensions of variables in NetCDF files are ordered so as to specify whether the data is stored in X-major, Y-major, or Z-major order.  
The fastest increasing dimension is last, consistent with the dimension ordering of FORTRAN arrays.
B<ncdf2vdf> requires that the Y dimension precedes the X dimension in the ordering of the dimensions in the NetCDF file.  This is consistent with the dimension ordering of WRF output files.  There is no Z dimension ordering requirement. 

=head1 HISTORY

Last updated on $Date$
