=begin comment

$Id$

=end comment

=head1 NAME

vdfls - List directory contents of a VAPOR Data Collection

=head1 SYNOPSIS

B<vdfls> [options] I<vdffile>

=head1 DESCRIPTION

B<vdfls> will list information about the files that make up a VAPOR Data
Collection (VDC) associated with the named .vdf file, I<vdffile>.
B<vdfls> provides infomration similar to that of the UNIX B<ls> command.


=head1 OPTIONS

=over 4

=item -debug

Turn on debugging mode. Currently not implemented.

=item -help 

Print a usage statement and then exit.

=item -long

Use a long listing format.

=item -sort E<lt>orderE<gt>

Change the default sorting order of the listing to I<order>, where
I<order> is one of B<time>, B<level>, or B<varname>.

=back


=head1 SEE ALSO

vdfcreate

I<An Overview of VAPOR Data Collections>


=head1 NOTES

=head1 HISTORY

Last updated on $Date$
