=begin comment

$Id$

=end comment

=head1 NAME

wrf2vdf - Transform WRF netCDF data into a VDC

=head1 SYNOPSIS

B<wrf2vdf> [options] I<vdffile> I<wrf_ncdf_file...> 

=head1 DESCRIPTION

B<wrf2vdf> reads 3D and 2D variables from one ore more WRF netCDF file,
wavelet transforms the data, and stores it in the VDC associated with
the .vdf file I<vdffile>.

=head1 OPTIONS

=over 4

=item -varnames E<lt>varsE<gt>

Variables to convert.  A colon delimited list of the 3D and 2D variables
you wish to transform, as their names appear in the .vdf file, I<vdffile>.
The variable B<ELEVATION> will always be converted (unless the B<-noelev>
option is present).  The default is all 3D and 2D variables defined in
both the .vdf file and the WRF netCDF file.

=item -numts E<lt>numberE<gt>

Specify the maximum number of time steps to convert. After converting
number time steps, no further processing will take place.

=item -noelev 

Specifies that no B<ELEVATION> variable will be generated.  This option
is useful for adding variables to a VDC when the B<ELEVATION> variable
has already been calculated, or if the WRF NetCDF files do not contain
B<PH> and B<PHB>  

=item -level E<lt>levelE<gt> 

See raw2vdf

=item -help 

Print a usage statement and then exit.

=item -quiet 

Operate quietly, only reporting fatal errors.

=back

=head1 EXAMPLES

The command 

    wrf2vdf mydata.vdf wrfout1.ncdf wrfout2.ncdf wrfout3.ncdf 

transforms all of the variables at all of the time steps found in the
WRF netCDF files B<wfout1.ncdf>, B<wrfout2.ncdf>, and B<wrfout3.ncdf> that
match the variable names and time stamps found in B<mydata.vdf>.

The command 

    wrf2vdf -vars3d U:V:W mydata.vdf wrfout1.ncdf wrfout2.ncdf wrfout3.ncdf 

is similar to the above example except that the variables are limited
to the three 3D wind components, B<U>, B<V>, and B<W>.

=head1 SEE ALSO

wrfvdfcreate, ncdf2vdf, raw2vdf 

I<Conversion of WRF-ARW datafiles to a VAPOR VDC>

=head1 HISTORY

Last updated on $Date$
