=begin comment

$Id$

=end comment

=head1 NAME

wrfvdfcreate - Generate a VDF metadata file for a WRF data set

=head1 SYNOPSIS

B<wrfvdfcreate> [options] I<wrf_ncdf_file...> I<vdffile>

=head1 DESCRIPTION

B<wrfvdfcreate> generates a .vdf metafile that will define a VAPOR Data
Collection (VDC) suitable for containing Weather Research Forecast
(WRF) simulation output. In the first form of the command one or more
WRF netCDF files are used as templates for generating I<vdffile>. This
is the recommended usage. 

=head1 OPTIONS

=over 4

=item -vars3d E<lt>varsE<gt>

A colon-delimited list of names of 3D variables (as they appear in the
WRF file) to include in the .vdf file.  The arguments to B<-varnames>
need not exclusively be WRF variables--for example, derived variables
(such as vorticity) that are stored in a netCDF file with the same
dimensions and B<PH>, B<PHB>, and B<Times> variables can be converted
as well. In the first form of the command the default is to convert all
3D variables found in the first of the WRF netCDF input files.

=item -vars2d E<lt>varsE<gt>

A colon-delimited list of names of 2D variables. See B<-vars3d>.

=item <-dervars> E<lt>varsE<gt>

A colon-delimited list of variables that are to be derived from WRF data during 
conversion with the wrf2vdf command.  These include: 
 
B<PHNorm_>: the normalized geopotential (PH+PHB)/PHB; 
  
B<UVW_>: the three-dimensional wind speed (U^2+V^2+W^2)^1/2; 
 
B<UV_>: the two-dimensional wind speed (U^2+V^2)^1/2; 
 
B<omZ_>: a rough estimate of the vertical vorticity; 
 
B<PFull_>: the full pressure P+PB; 
 
B<PNorm_>: the normalized pressure (P+PB)/PB; 
  
B<Theta_>: the potential temperature T+300; and 
 
B<TK_>: the temperature in Kelvin, B<TK_> = (B<T> + 300) *
((B<P>+B<PB>)/100000)^0.286
 
No other arguments to this option may be given.  

=item -atypvars E<lt>varsE<gt>

Atypical variable names.  When calculating the B<ELEVATION> variable
as well as several derived variables (see below), B<wrfvdfcreate>
and B<wrf2vdf> assume that the wind components are named B<U>, B<V>,
and B<W>, the perturbation pressure is named B<P>, the base pressure is
B<PB>, the perturbation geopotential is B<PH>, and the base geopotential is
B<PHB>.  If any one of these variables has a name other than these (for
example, some users have wind components named U1, V1, W1), this option
must be given.  Its argument is a colon delimited list of the actual
names of the variables which are typically named U:V:W:PH:PHB:P:PB:T.
The list must be given in that order and contain all 8 elements, even
if some of these eight variables have the expected names.

=item -level E<lt>levelE<gt>

See vdfcreate.

=item -comment E<lt>stringE<gt>

See vdfcreate.

=item -bs E<lt>NXxNYxNZE<gt>

See vdfcreate.

=item -nfilter E<lt>nE<gt>

See vdfcreate.

=item -nlifting E<lt>nE<gt>
 
See vdfcreate.

=item -help 

Print a usage statement and then exit.

=back

=head1 EXAMPLES


The command 

    wrfvdfcreate -vars3d P:T -level 2 wrf1.ncdf wrf2.ncdf wrf3.ncdf mydata.vdf

will construct a VDF file, B<mydata.vdf> that will contain the B<P>
and B<T> variable names for all time steps found in the WRF netCDF files
B<wrf1.ncdf>, B<wrf2.ncdf>, and B<wrf3.ncdf>.


=head1 SEE ALSO

vdfcreate, wrf2vdf,

I<Conversion of WRF-ARW datafiles to a VAPOR VDC>

=head1 HISTORY

Last updated on $Date$
