TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = roms2vdf
FILES = roms2vdf
HEADERS = 2vdf


LIBRARIES = vdf proj common $(NETCDF_LIBS) udunits2 expat

include ${TOP}/make/config/base.mk
