TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = vdfcreate
FILES = vdfcreate

#LIB_DEFS = vdf.def

LIBRARIES = vdf proj common udunits2 $(NETCDF_LIBS) expat

include ${TOP}/make/config/base.mk

