TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = wrf2vdf
FILES = wrf2vdf


#LIB_DEFS = vdf.def
  
LIBRARIES = vdf common netcdf $(EXPAT_LIB)

include ${TOP}/make/config/base.mk
