TOP = ../..

include ${TOP}/make/config/prebase.mk

PROGRAM = wrf2vdf
FILES = wrf2vdf


#LIB_DEFS = vdf.def

LIBRARIES = vdf proj common $(NETCDF_LIBS) expat

include ${TOP}/make/config/base.mk
